fix worflow error

diff --git a/.github/workflows/restrict_merge_to_main.yaml b/.github/workflows/restrict_merge_to_main.yaml
--- a/.github/workflows/restrict_merge_to_main.yaml
+++ b/.github/workflows/restrict_merge_to_main.yaml
@@ -8,8 +8,8 @@ jobs:
   check_branch:
     runs-on: ubuntu-latest
     steps:
-      -name: Check Branch
-      if: github.base_ref == 'main' && github.head_ref !='develop'
-      run: |
-        echo "ERROR: You can only merge to 'main' from 'develop'."
-        exit 1
+      - name: Check Branch
+        if: github.base_ref == 'main' && github.head_ref !='develop'
+        run: |
+          echo "ERROR: You can only merge to 'main' from 'develop'."
+          exit 1
